package com.aistudio.orbit.forensics.patterns

import com.aistudio.orbit.model.*

object CrimePatternLibrary {

    val patterns: List<CrimePattern> = listOf(
        CrimePattern(
            id = "PAT_AML_FAN_IN",
            code = "AML_FAN_IN",
            nameEn = "A. Fan-In (Consolidation)",
            nameFa = "A. تجمیع و ادغام (Fan-In)",
            category = CrimeCategory.MONEY_LAUNDERING,
            descriptionEn = "Many source addresses send funds to one destination.",
            descriptionFa = "ارسال وجه از آدرس‌های متعدد به یک مقصد واحد.",
            behavioralIndicatorsEn = listOf("High input to output ratio", "Source dispersion"),
            behavioralIndicatorsFa = listOf("نسبت بالای ورودی به خروجی", "پراکندگی مبداها"),
            detectionRules = "Rule: inputs.size >= 5 and outputs.size <= 2",
            scoringModel = "Consolidation ratio & time concentration",
            confidenceInterpretationEn = "May indicate consolidation of illicit funds or legitimate exchange/merchant aggregation.",
            confidenceInterpretationFa = "ممکن است نشان‌دهنده تجمیع وجوه غیرقانونی یا تجمیع مشروع صرافی/درگاه باشد.",
            references = listOf("FATF Red Flags for Virtual Assets")
        ),
        CrimePattern(
            id = "PAT_AML_FAN_OUT",
            code = "AML_FAN_OUT",
            nameEn = "B. Fan-Out (Dispersion)",
            nameFa = "B. خردسازی و توزیع (Fan-Out)",
            category = CrimeCategory.MONEY_LAUNDERING,
            descriptionEn = "One address distributes funds to many destinations.",
            descriptionFa = "توزیع وجه از یک آدرس به چندین مقصد مجزا.",
            behavioralIndicatorsEn = listOf("High output fan-out ratio", "Uniform payment amounts"),
            behavioralIndicatorsFa = listOf("توزیع بالا به خروجی‌ها", "مبالغ یکنواخت پرداختی"),
            detectionRules = "Rule: outputs.size >= 5 and inputs.size <= 2",
            scoringModel = "Dispersion Entropy",
            confidenceInterpretationEn = "Analytical hypothesis requiring contextual corroboration.",
            confidenceInterpretationFa = "فرضیه تحلیلی که نیازمند تایید شواهد زمینه‌ای است.",
            references = listOf("FATF Red Flags")
        ),
        CrimePattern(
            id = "PAT_AML_STRUCTURING",
            code = "AML_STRUCTURING",
            nameEn = "C. Structuring / Smurfing Indicators",
            nameFa = "C. شاخص‌های خردسازی (Structuring/Smurfing)",
            category = CrimeCategory.STRUCTURING_SMURFING,
            descriptionEn = "Repeated transfers that may indicate deliberate fragmentation.",
            descriptionFa = "تراکنش‌های مکرر که نشان‌دهنده خردسازی عمدی مبالغ است.",
            behavioralIndicatorsEn = listOf("Repeated amounts", "Amounts close to configured thresholds"),
            behavioralIndicatorsFa = listOf("مبالغ تکراری", "مبالغ نزدیک به آستانه‌های نظارتی"),
            detectionRules = "Rule: Recurring txs within small timeframe below thresholds",
            scoringModel = "Amount variance & temporal frequency",
            confidenceInterpretationEn = "Potential deliberate evasion of reporting thresholds.",
            confidenceInterpretationFa = "احتمال تلاش عمدی برای دور زدن آستانه‌های گزارش‌دهی.",
            references = listOf("FATF Red Flags")
        ),
        CrimePattern(
            id = "PAT_AML_LAYERING",
            code = "AML_LAYERING",
            nameEn = "D. Layering",
            nameFa = "D. لایه‌بندی مالی (Layering)",
            category = CrimeCategory.MONEY_LAUNDERING,
            descriptionEn = "Multi-hop movement through intermediary addresses.",
            descriptionFa = "حرکت وجوه از طریق چندین آدرس واسطه (هاپ‌های متعدد).",
            behavioralIndicatorsEn = listOf("High hop count", "Short time between hops"),
            behavioralIndicatorsFa = listOf("تعداد بالای هاپ", "زمان کوتاه بین انتقال‌ها"),
            detectionRules = "Rule: path_length >= 3 with consistent amounts",
            scoringModel = "Graph path depth and value retention",
            confidenceInterpretationEn = "Indicates attempt to obscure provenance.",
            confidenceInterpretationFa = "نشانگر تلاش برای مخفی‌سازی منشا وجوه است.",
            references = listOf("FATF Typologies")
        ),
        CrimePattern(
            id = "PAT_AML_PEEL_CHAIN",
            code = "AML_PEEL_CHAIN",
            nameEn = "E. Peel Chain",
            nameFa = "E. زنجیره پوست‌کنی (Peel Chain)",
            category = CrimeCategory.MONEY_LAUNDERING,
            descriptionEn = "Repeated partial transfers where one address continues moving a remainder.",
            descriptionFa = "انتقال‌های جزئی مکرر که در آن یک آدرس مابقی وجه را مدام به جلو می‌راند.",
            behavioralIndicatorsEn = listOf("Repeated 2-output outgoing txs", "Asymmetric output values"),
            behavioralIndicatorsFa = listOf("تراکنش‌های متوالی با ۲ خروجی", "ارزش نامتقارن خروجی‌ها"),
            detectionRules = "Rule: Consecutive outgoing txs >= 3 with outputs.size == 2",
            scoringModel = "Topology & Change Output Ratio",
            confidenceInterpretationEn = "Signature money-laundering technique.",
            confidenceInterpretationFa = "تکنیک شاخص پولشویی.",
            references = listOf("US DOJ Enforcement Framework")
        ),
        CrimePattern(
            id = "PAT_AML_RAPID_PASS_THROUGH",
            code = "AML_RAPID_PASS_THROUGH",
            nameEn = "F. Rapid Pass-Through",
            nameFa = "F. انتقال سریع و بی‌درنگ",
            category = CrimeCategory.HIGH_VELOCITY_TRANSIT,
            descriptionEn = "Addresses that receive funds and move most or all of them shortly afterward.",
            descriptionFa = "آدرس‌هایی که وجوه را دریافت کرده و بلافاصله بیشتر یا تمام آن را منتقل می‌کنند.",
            behavioralIndicatorsEn = listOf("Incoming/Outgoing within minutes", "Minimal balance retention"),
            behavioralIndicatorsFa = listOf("ورود و خروج در چند دقیقه", "حداقل نگهداری موجودی"),
            detectionRules = "Rule: delta_time < 30m and high volume matching",
            scoringModel = "Holding duration & volume correlation",
            confidenceInterpretationEn = "May indicate a transit wallet, mule, or proxy.",
            confidenceInterpretationFa = "احتمالاً نشان‌دهنده یک کیف‌پول واسطه، حساب اجاره‌ای یا پروکسی است.",
            references = listOf("AMLD6 Indicators")
        ),
        CrimePattern(
            id = "PAT_AML_DORMANT_ACTIVATION",
            code = "AML_DORMANT_ACTIVATION",
            nameEn = "G. Dormant Activation",
            nameFa = "G. فعال‌سازی حساب خوابیده",
            category = CrimeCategory.BEHAVIORAL_ANOMALY,
            descriptionEn = "Addresses with long inactivity followed by unusual activity.",
            descriptionFa = "آدرس‌هایی با عدم فعالیت طولانی که به ناگهان فعالیت غیرعادی نشان می‌دهند.",
            behavioralIndicatorsEn = listOf("Dormancy > 180 days", "Sudden high-value transfers"),
            behavioralIndicatorsFa = listOf("عدم فعالیت بیش از ۱۸۰ روز", "انتقال ناگهانی با ارزش بالا"),
            detectionRules = "Rule: gap > 180 days",
            scoringModel = "Dormancy interval delta",
            confidenceInterpretationEn = "Could indicate compromised keys or old scam liquidation.",
            confidenceInterpretationFa = "می‌تواند نشان‌دهنده نشت کلید خصوصی یا نقد کردن دارایی‌های مسروقه قدیمی باشد.",
            references = listOf("Elliptic Forensic Guide")
        ),
        CrimePattern(
            id = "PAT_AML_RAPID_SUCCESSION",
            code = "AML_RAPID_SUCCESSION",
            nameEn = "H. Rapid Succession",
            nameFa = "H. توالی سریع تراکنش‌ها",
            category = CrimeCategory.HIGH_VELOCITY_TRANSIT,
            descriptionEn = "Multiple transfers occurring within unusually short intervals.",
            descriptionFa = "تراکنش‌های متعددی که در فواصل زمانی بسیار کوتاه رخ می‌دهند.",
            behavioralIndicatorsEn = listOf("Multiple txs in tight time window"),
            behavioralIndicatorsFa = listOf("چندین تراکنش در بازه زمانی بسیار فشرده"),
            detectionRules = "Rule: TX frequency > threshold",
            scoringModel = "Temporal burstiness",
            confidenceInterpretationEn = "Automated execution or urgent liquidation.",
            confidenceInterpretationFa = "اجرای خودکار رباتیک یا تلاش برای نقد کردن فوری.",
            references = listOf("FATF Red Flags")
        ),
        CrimePattern(
            id = "PAT_AML_CYCLIC_FLOW",
            code = "AML_CYCLIC_FLOW",
            nameEn = "I. Cyclic Flow",
            nameFa = "I. جریان مدور",
            category = CrimeCategory.MONEY_LAUNDERING,
            descriptionEn = "Funds returning through a path to a previous address/entity.",
            descriptionFa = "بازگشت وجوه از طریق یک مسیر به آدرس یا موجودیت قبلی.",
            behavioralIndicatorsEn = listOf("Graph cycle detected"),
            behavioralIndicatorsFa = listOf("تشخیص حلقه در گراف"),
            detectionRules = "Rule: Cycle detection path_length 2..5",
            scoringModel = "Cycle path analysis",
            confidenceInterpretationEn = "Potential artificial volume or obfuscation.",
            confidenceInterpretationFa = "احتمال حجم‌سازی صوری یا مخفی‌سازی جریان مالی.",
            references = listOf("FATF Red Flags")
        ),
        CrimePattern(
            id = "PAT_AML_ROUND_TRIPPING",
            code = "AML_ROUND_TRIPPING",
            nameEn = "J. Round-Tripping / Wash-Like Cycle",
            nameFa = "J. چرخه شستشوی دارایی (Round-Tripping)",
            category = CrimeCategory.MONEY_LAUNDERING,
            descriptionEn = "Repeated circulation of assets through related addresses.",
            descriptionFa = "چرخش مکرر دارایی‌ها در میان آدرس‌های مرتبط.",
            behavioralIndicatorsEn = listOf("Repeated bilateral transfers"),
            behavioralIndicatorsFa = listOf("انتقال‌های دوطرفه مکرر"),
            detectionRules = "Rule: Frequency of circular loops",
            scoringModel = "Cycle detection",
            confidenceInterpretationEn = "Indicator only. Does not claim market manipulation alone.",
            confidenceInterpretationFa = "صرفاً یک شاخص تحلیلی است و به تنهایی دلیل بر دستکاری بازار نیست.",
            references = listOf("SEC Forensic Guidelines")
        ),
        CrimePattern(
            id = "PAT_AML_EXCHANGE_HOPPING",
            code = "AML_EXCHANGE_HOPPING",
            nameEn = "K. Exchange Hopping",
            nameFa = "K. پرش میان صرافی‌ها",
            category = CrimeCategory.MONEY_LAUNDERING,
            descriptionEn = "Rapid movement across multiple exchange/service labels.",
            descriptionFa = "انتقال سریع وجوه در میان چندین صرافی یا سرویس مختلف.",
            behavioralIndicatorsEn = listOf("Withdrawal from Exch A, deposit to Exch B"),
            behavioralIndicatorsFa = listOf("برداشت از صرافی الف و واریز به صرافی ب"),
            detectionRules = "Rule: Path traverses >= 2 exchanges",
            scoringModel = "Entity exposure analysis",
            confidenceInterpretationEn = "Arbitrage or jurisdiction obfuscation.",
            confidenceInterpretationFa = "آربیتراژ یا تلاش برای مخفی‌سازی حوزه‌های قضایی.",
            references = listOf("FATF Typologies")
        ),
        CrimePattern(
            id = "PAT_AML_MIXER_EXPOSURE",
            code = "AML_MIXER_EXPOSURE",
            nameEn = "L. Mixer / Tumbler Exposure",
            nameFa = "L. ارتباط با میکسر/تامبلر",
            category = CrimeCategory.MIXER_OBFUSCATION,
            descriptionEn = "Interaction with known or externally tagged mixer/tumbler services.",
            descriptionFa = "تعامل با سرویس‌های شناخته‌شده میکسر یا تامبلر جهت ناشناس‌سازی.",
            behavioralIndicatorsEn = listOf("Direct/Indirect flow to mixer entity"),
            behavioralIndicatorsFa = listOf("ارتباط مستقیم/غیرمستقیم با هویت میکسر"),
            detectionRules = "Rule: EntityLabel == MIXER in path",
            scoringModel = "Exposure distance & volume",
            confidenceInterpretationEn = "High-risk indicator for deliberate obfuscation.",
            confidenceInterpretationFa = "شاخص پرخطر برای مخفی‌سازی عمدی ردپای مالی.",
            references = listOf("FATF Red Flags")
        ),
        CrimePattern(
            id = "PAT_AML_BRIDGE_HOPPING",
            code = "AML_BRIDGE_HOPPING",
            nameEn = "M. Bridge Hopping",
            nameFa = "M. پرش میان پل‌های بلاکچینی",
            category = CrimeCategory.MONEY_LAUNDERING,
            descriptionEn = "Movement across blockchain bridges.",
            descriptionFa = "جابه‌جایی دارایی‌ها از طریق پل‌های بلاکچینی میان شبکه‌های مختلف.",
            behavioralIndicatorsEn = listOf("Interaction with cross-chain bridge smart contracts"),
            behavioralIndicatorsFa = listOf("تعامل با قراردادهای هوشمند پل‌های میان‌زنجیره‌ای"),
            detectionRules = "Rule: EntityLabel == BRIDGE",
            scoringModel = "Bridge interaction analysis",
            confidenceInterpretationEn = "Chain-hopping for obfuscation or simple DeFi usage.",
            confidenceInterpretationFa = "پرش بین‌زنجیره‌ای برای پولشویی یا استفاده ساده از DeFi.",
            references = listOf("Chainalysis Typologies")
        ),
        CrimePattern(
            id = "PAT_AML_MULTI_ASSET_CONVERSION",
            code = "AML_MULTI_ASSET_CONVERSION",
            nameEn = "N. Multi-Asset Conversion",
            nameFa = "N. تبدیل چندگانه دارایی‌ها",
            category = CrimeCategory.MONEY_LAUNDERING,
            descriptionEn = "Rapid switching between assets.",
            descriptionFa = "تغییر و تبدیل سریع میان دارایی‌های رمزنگاری‌شده مختلف.",
            behavioralIndicatorsEn = listOf("DEX swaps involving multiple tokens in short time"),
            behavioralIndicatorsFa = listOf("مبادله از طریق DEX شامل چندین توکن در زمان کوتاه"),
            detectionRules = "Rule: Asset diversity > threshold within timeframe",
            scoringModel = "Asset sequence analysis",
            confidenceInterpretationEn = "Could indicate chain peeling or DeFi usage.",
            confidenceInterpretationFa = "ممکن است نشانگر پوست‌کنی زنجیره یا استفاده از دیفای باشد.",
            references = listOf("FATF Red Flags")
        ),
        CrimePattern(
            id = "PAT_AML_CONSOLIDATION",
            code = "AML_CONSOLIDATION",
            nameEn = "O. Consolidation",
            nameFa = "O. تجمیع نهایی",
            category = CrimeCategory.MONEY_LAUNDERING,
            descriptionEn = "Many addresses eventually transferring funds into a smaller number of destinations.",
            descriptionFa = "انتقال وجوه از آدرس‌های متعدد به تعداد محدودی آدرس مقصد.",
            behavioralIndicatorsEn = listOf("Multiple independent paths converging"),
            behavioralIndicatorsFa = listOf("همگرایی چندین مسیر مستقل"),
            detectionRules = "Rule: Graph convergence metrics",
            scoringModel = "Network centrality",
            confidenceInterpretationEn = "Final stage of laundering or legitimate aggregation.",
            confidenceInterpretationFa = "مرحله نهایی پولشویی یا تجمیع مشروع شرکتی.",
            references = listOf("FATF Red Flags")
        ),
        CrimePattern(
            id = "PAT_AML_DISPERSION",
            code = "AML_DISPERSION",
            nameEn = "P. Dispersion",
            nameFa = "P. پراکندگی",
            category = CrimeCategory.MONEY_LAUNDERING,
            descriptionEn = "One source distributing funds across many addresses.",
            descriptionFa = "توزیع وجوه از یک منبع به تعداد زیادی آدرس دیگر.",
            behavioralIndicatorsEn = listOf("Funds spreading out over multiple hops"),
            behavioralIndicatorsFa = listOf("پراکنده شدن وجوه در چندین هاپ"),
            detectionRules = "Rule: Graph divergence metrics",
            scoringModel = "Network out-degree spreading",
            confidenceInterpretationEn = "Initial stage of obfuscation.",
            confidenceInterpretationFa = "مرحله اولیه پنهان‌سازی (Layering).",
            references = listOf("FATF Red Flags")
        ),
        CrimePattern(
            id = "PAT_AML_BURST_ACTIVITY",
            code = "AML_BURST_ACTIVITY",
            nameEn = "Q. Burst Activity",
            nameFa = "Q. فعالیت انفجاری",
            category = CrimeCategory.BEHAVIORAL_ANOMALY,
            descriptionEn = "Abnormal concentration of transactions within a short time period.",
            descriptionFa = "تمرکز غیرعادی تراکنش‌ها در یک بازه زمانی کوتاه.",
            behavioralIndicatorsEn = listOf("High transaction count / temporal window"),
            behavioralIndicatorsFa = listOf("تعداد بالای تراکنش / پنجره زمانی"),
            detectionRules = "Rule: TX frequency > baseline * threshold",
            scoringModel = "Temporal baseline deviation",
            confidenceInterpretationEn = "Automated scripting or unusual urgency.",
            confidenceInterpretationFa = "اجرای اسکریپت خودکار یا فوریت غیرمعمول.",
            references = listOf("FATF Red Flags")
        ),
        CrimePattern(
            id = "PAT_AML_HIGH_VELOCITY",
            code = "AML_HIGH_VELOCITY",
            nameEn = "R. High Velocity",
            nameFa = "R. سرعت گردش بالا",
            category = CrimeCategory.HIGH_VELOCITY_TRANSIT,
            descriptionEn = "Unusually rapid movement of value.",
            descriptionFa = "جابه‌جایی غیرعادی و سریع ارزش مالی.",
            behavioralIndicatorsEn = listOf("Large volume moved in short duration"),
            behavioralIndicatorsFa = listOf("حجم کلان جابه‌جا شده در مدت کوتاه"),
            detectionRules = "Rule: Volume / Time > threshold",
            scoringModel = "Velocity metrics",
            confidenceInterpretationEn = "Transit node behavior.",
            confidenceInterpretationFa = "رفتار گره ترانزیتی.",
            references = listOf("FATF Red Flags")
        ),
        CrimePattern(
            id = "PAT_AML_ADDRESS_REUSE",
            code = "AML_ADDRESS_REUSE",
            nameEn = "S. Address Reuse / Operational Reuse",
            nameFa = "S. استفاده مجدد و عملیاتی از آدرس",
            category = CrimeCategory.BEHAVIORAL_ANOMALY,
            descriptionEn = "Recurring operational relationships.",
            descriptionFa = "روابط عملیاتی تکرارشونده و استفاده مجدد از آدرس‌ها.",
            behavioralIndicatorsEn = listOf("Same counterparty engaged repeatedly over time"),
            behavioralIndicatorsFa = listOf("تعامل مکرر با یک طرف مقابل یکسان در طول زمان"),
            detectionRules = "Rule: Edge frequency > threshold",
            scoringModel = "Counterparty repetition",
            confidenceInterpretationEn = "Establishes a strong operational link.",
            confidenceInterpretationFa = "وجود پیوند عملیاتی قوی را اثبات می‌کند.",
            references = listOf("Blockchain Privacy Guidelines")
        ),
        CrimePattern(
            id = "PAT_AML_HIGH_RISK_EXPOSURE",
            code = "AML_HIGH_RISK_EXPOSURE",
            nameEn = "T. High-Risk Service Exposure",
            nameFa = "T. مواجهه با سرویس‌های پرخطر",
            category = CrimeCategory.EXTERNAL_EXPOSURE,
            descriptionEn = "Interaction with addresses/services carrying verified external risk labels.",
            descriptionFa = "تعامل با آدرس‌ها یا سرویس‌هایی که برچسب ریسک خارجی تایید شده دارند.",
            behavioralIndicatorsEn = listOf("Exposure to darknet, gambling, or high-risk exchanges"),
            behavioralIndicatorsFa = listOf("ارتباط با دارک‌نت، قمار یا صرافی‌های پرخطر"),
            detectionRules = "Rule: EntityRiskLevel == HIGH",
            scoringModel = "External intelligence",
            confidenceInterpretationEn = "Directly relies on intelligence provider accuracy.",
            confidenceInterpretationFa = "مستقیماً به دقت ارائه‌دهنده اطلاعات خارجی بستگی دارد.",
            references = listOf("FATF Red Flags")
        ),
        CrimePattern(
            id = "PAT_AML_SCAM_COLLECTION",
            code = "AML_SCAM_COLLECTION",
            nameEn = "U. Possible Scam Collection Pattern",
            nameFa = "U. الگوی احتمالی جمع‌آوری وجوه کلاهبرداری",
            category = CrimeCategory.FRAUD,
            descriptionEn = "Patterns potentially consistent with scam collection behavior.",
            descriptionFa = "الگوهایی که به طور بالقوه با رفتار جمع‌آوری وجوه کلاهبرداری سازگارند.",
            behavioralIndicatorsEn = listOf("Many small unassociated deposits"),
            behavioralIndicatorsFa = listOf("واریزهای خرد متعدد و نامرتبط"),
            detectionRules = "Rule: High in-degree, low out-degree, unique senders",
            scoringModel = "In-degree uniqueness",
            confidenceInterpretationEn = "Requires victim reports for confirmation.",
            confidenceInterpretationFa = "نیازمند گزارش قربانیان برای تایید قطعی است.",
            references = listOf("Chainalysis Scam Reports")
        ),
        CrimePattern(
            id = "PAT_AML_RANSOM_PAYMENT",
            code = "AML_RANSOM_PAYMENT",
            nameEn = "V. Possible Ransom Payment Pattern",
            nameFa = "V. الگوی احتمالی پرداخت باج‌افزار",
            category = CrimeCategory.RANSOMWARE,
            descriptionEn = "Patterns potentially consistent with ransom-related collection and subsequent movement.",
            descriptionFa = "الگوهایی که به طور بالقوه با جمع‌آوری باج و انتقال بعدی آن سازگارند.",
            behavioralIndicatorsEn = listOf("Exact round numbers, split developer/affiliate fees"),
            behavioralIndicatorsFa = listOf("اعداد رند دقیق، تقسیم سهم توسعه‌دهنده/مجری"),
            detectionRules = "Rule: specific value distribution & forwarding",
            scoringModel = "Ransom distribution topology",
            confidenceInterpretationEn = "Requires IOCs or threat intel matching.",
            confidenceInterpretationFa = "نیازمند انطباق با شاخص‌های سازش (IOC) و اطلاعات تهدیدات است.",
            references = listOf("Ransomware Tracing Guidelines")
        ),
        CrimePattern(
            id = "PAT_AML_EXTORTION",
            code = "AML_EXTORTION",
            nameEn = "W. Possible Extortion / Coercive Payment Pattern",
            nameFa = "W. الگوی احتمالی پرداخت اجباری/اخاذی",
            category = CrimeCategory.EXTORTION_COERCION,
            descriptionEn = "Patterns associated with extortion payments (no legal conclusion).",
            descriptionFa = "الگوهای مرتبط با باج‌گیری و پرداخت‌های اجباری (بدون نتیجه‌گیری قطعی حقوقی).",
            behavioralIndicatorsEn = listOf("Single suspicious payment matching known extortion demands"),
            behavioralIndicatorsFa = listOf("پرداخت مشکوک منفرد منطبق بر درخواست‌های شناخته‌شده اخاذی"),
            detectionRules = "Rule: External context + Tx isolation",
            scoringModel = "Contextual analysis",
            confidenceInterpretationEn = "Behavioral heuristic, not legal proof.",
            confidenceInterpretationFa = "نشانه تحلیلی رفتاری، نه اثبات حقوقی.",
            references = listOf("Cybercrime Investigations")
        ),
        CrimePattern(
            id = "PAT_AML_ILLICIT_SERVICE",
            code = "AML_ILLICIT_SERVICE",
            nameEn = "X. Possible Illicit-Service Payment",
            nameFa = "X. پرداخت احتمالی به سرویس‌های غیرقانونی",
            category = CrimeCategory.FRAUD,
            descriptionEn = "Behavioral patterns potentially associated with payments to known illicit-service entities.",
            descriptionFa = "الگوهای رفتاری مرتبط با پرداخت به نهادهای سرویس‌دهنده غیرقانونی.",
            behavioralIndicatorsEn = listOf("Interaction with flagged wallets"),
            behavioralIndicatorsFa = listOf("تعامل با کیف‌پول‌های نشان‌دار"),
            detectionRules = "Rule: EntityLabel == ILLICIT_SERVICE",
            scoringModel = "External intelligence",
            confidenceInterpretationEn = "Rely on threat intel.",
            confidenceInterpretationFa = "مبتنی بر اطلاعات تهدیدات سایبری.",
            references = listOf("FATF Red Flags")
        ),
        CrimePattern(
            id = "PAT_AML_SANCTIONS_EXPOSURE",
            code = "AML_SANCTIONS_EXPOSURE",
            nameEn = "Y. Sanctions Exposure",
            nameFa = "Y. مواجهه با نهادهای تحریم‌شده",
            category = CrimeCategory.SANCTIONS_EVASION,
            descriptionEn = "Direct or indirect interaction with sanctioned entities/addresses where reliable external data exists.",
            descriptionFa = "تعامل مستقیم یا غیرمستقیم با نهادها/آدرس‌های تحریم‌شده بر اساس داده‌های موثق خارجی.",
            behavioralIndicatorsEn = listOf("Exposure to OFAC or UN sanctioned entities"),
            behavioralIndicatorsFa = listOf("مواجهه با نهادهای تحریم‌شده OFAC یا سازمان ملل"),
            detectionRules = "Rule: EntityLabel == SANCTIONED",
            scoringModel = "Intelligence cross-reference",
            confidenceInterpretationEn = "High confidence if direct, diminishes with hops.",
            confidenceInterpretationFa = "در صورت ارتباط مستقیم اطمینان بالا، با افزایش تعداد هاپ کاهش می‌یابد.",
            references = listOf("OFAC SDN List Guidelines")
        ),
        CrimePattern(
            id = "PAT_AML_PEP_EXPOSURE",
            code = "AML_PEP_EXPOSURE",
            nameEn = "Z. PEP / High-Profile Entity Exposure",
            nameFa = "Z. ارتباط با اشخاص مهم سیاسی (PEP)",
            category = CrimeCategory.EXTERNAL_EXPOSURE,
            descriptionEn = "External intelligence relationships while maintaining strict separation between identity information and blockchain evidence.",
            descriptionFa = "ارتباطات اطلاعاتی خارجی مرتبط با افراد دارای ریسک سیاسی بالا.",
            behavioralIndicatorsEn = listOf("Interaction with identified PEP wallets"),
            behavioralIndicatorsFa = listOf("تعامل با کیف‌پول‌های شناسایی‌شده اشخاص مهم سیاسی"),
            detectionRules = "Rule: EntityLabel == PEP",
            scoringModel = "Intelligence cross-reference",
            confidenceInterpretationEn = "Requires off-chain identity corroboration.",
            confidenceInterpretationFa = "نیازمند تایید هویت خارج از زنجیره است.",
            references = listOf("FATF PEP Guidance")
        )
    )

    val referenceCases: List<ReferenceCase> = emptyList() // Or populate with some reference cases later
}

