package com.aistudio.orbit.localization

import com.aistudio.orbit.repository.AppLanguage

fun String.toPersianDigits(isFa: Boolean = true): String {
    if (!isFa) return this
    val persianDigits = charArrayOf('۰', '۱', '۲', '۳', '۴', '۵', '۶', '۷', '۸', '۹')
    val sb = StringBuilder(this.length)
    for (ch in this) {
        if (ch in '0'..'9') {
            sb.append(persianDigits[ch - '0'])
        } else {
            sb.append(ch)
        }
    }
    return sb.toString()
}

fun Int.toPersianDigits(isFa: Boolean = true): String = this.toString().toPersianDigits(isFa)
fun Long.toPersianDigits(isFa: Boolean = true): String = this.toString().toPersianDigits(isFa)
fun Double.toPersianDigits(isFa: Boolean = true): String = this.toString().toPersianDigits(isFa)

data class ForensicStrings(
    val appTitle: String,
    val appSubtitle: String,
    val tabDashboard: String,
    val tabNewInvestigation: String,
    val tabCases: String,
    val tabGraph: String,
    val tabTasks: String,
    val tabApiSettings: String,
    val tabUserMgmt: String,
    
    // Investigation Stages
    val stage1Title: String,
    val stage2Title: String,
    val stage3Title: String,
    val stage4Title: String,
    val stage5Title: String,
    val stage6Title: String,
    val stage7Title: String,
    val nextStage: String,
    val prevStage: String,
    val rerunStage: String,
    
    // Investigation Entry
    val caseReferenceNumber: String,
    val caseTitle: String,
    val blockchainNetwork: String,
    val targetAddress: String,
    val addressPlaceholder: String,
    val investigationScope: String,
    val notesAndTags: String,
    val searchDepth: String,
    val queryLimit: String,
    val startInvestigation: String,
    val addressValidationSuccess: String,
    val addressValidationError: String,
    val addressFormatType: String,
    
    // Evidence Log
    val evidenceLogTitle: String,
    val evidenceLogSubtitle: String,
    val categoryObservedFact: String,
    val categoryAlgorithmResult: String,
    val categoryAttribution: String,
    val categoryBehavioralPattern: String,
    val categoryTemporalAnalysis: String,
    val categoryInvestigatorConclusion: String,
    val confidenceDefinitive: String,
    val confidenceHigh: String,
    val confidenceMedium: String,
    val confidenceHeuristic: String,
    val filterAllEvidence: String,
    val filterOnlyFacts: String,
    val filterOnlyPatterns: String,
    
    // Overview Metrics
    val balance: String,
    val totalReceived: String,
    val totalSent: String,
    val totalTransactions: String,
    val firstActivity: String,
    val lastActivity: String,
    val uniqueCounterparties: String,
    val riskIndicatorsDetected: String,
    
    // Currency Conversion
    val customCurrencyRates: String,
    val btcUsdRate: String,
    val usdTomanRate: String,
    val equivalentUsd: String,
    val equivalentToman: String,
    val editRates: String,
    
    // Transactions Table
    val transactionsTitle: String,
    val txHash: String,
    val time: String,
    val blockHeight: String,
    val direction: String,
    val amount: String,
    val fee: String,
    val counterparties: String,
    val dirIncoming: String,
    val dirOutgoing: String,
    val dirSelf: String,
    val dirMixed: String,
    val filterDirection: String,
    val filterMinAmount: String,
    
    // Crime Pattern Library & Matching
    val patternLibraryTitle: String,
    val patternMatchingSubtitle: String,
    val similarityScore: String,
    val matchedIndicatorsTitle: String,
    val conflictingIndicatorsTitle: String,
    val missingEvidenceTitle: String,
    val analyticalRecommendation: String,
    val referenceCasesTitle: String,
    val viewReferenceCase: String,
    
    // Temporal & Geographic Time
    val temporalAnalysisTitle: String,
    val temporalSubtitle: String,
    val hourlyActivityTehran: String,
    val hourlyActivityUtc: String,
    val dayOfWeekDistribution: String,
    val geographicCompatibilityTitle: String,
    val compatibilityPercentage: String,
    val candidateRegion: String,
    val workingHoursWindow: String,
    val temporalDisclaimer: String,
    
    // Graph
    val graphTitle: String,
    val zoomIn: String,
    val zoomOut: String,
    val resetView: String,
    val selectNodePrompt: String,
    val exportGraph: String,
    val exportPdfReport: String,
    
    // Counterparties & Pairwise
    val counterpartyMatrix: String,
    val counterpartyAddress: String,
    val interactionCount: String,
    val volumeReceived: String,
    val volumeSent: String,
    val netFlow: String,
    val pairwiseDeepDiveTitle: String,
    val directInteractions: String,
    val bilateralNetFlow: String,
    
    // Export & Reporting
    val exportDossierTitle: String,
    val exportTxtDossier: String,
    val exportCsvDataset: String,
    val exportJsonBundle: String,
    val downloadDossier: String,
    val exportSuccessMessage: String,
    
    // Settings & User Mgmt
    val settingsTitle: String,
    val languageSetting: String,
    val jalaliCalendarSetting: String,
    val tehranTimezoneSetting: String,
    val persianNumeralsSetting: String,
    val apiProvidersTitle: String,
    val testConnection: String,
    val connectionSuccess: String,
    val connectionFailed: String,
    val providerHelp: String,
    val primaryApiKey: String,
    val secondaryApiKey: String,
    val saveSettings: String,
    val userManagementTitle: String,
    val activeUser: String,
    val userRole: String,
    val togglePermission: String,
    val changePasswordTitle: String,
    val newPasswordLabel: String,
    val confirmPasswordLabel: String,
    val updatePasswordButton: String,
    
    // Actions & General
    val loadingBlockchainData: String,
    val analyzingPatterns: String,
    val savingCase: String,
    val deleteCase: String,
    val reopenCase: String,
    val noCasesFound: String,
    val close: String,
    val copyAddress: String,
    val copiedToClipboard: String,
    val errorOccurred: String,
    val disclaimerText: String
) {
    val targetAddressLabel: String get() = targetAddress
    val caseRefLabel: String get() = caseReferenceNumber
    val caseTitleLabel: String get() = caseTitle
}

object AppLocalization {

    val stringsFa = ForensicStrings(
        appTitle = "بیِّنة",
        appSubtitle = "سامانه پیشرفته فارنزیک مالی و هوشمندی ادله بلاکچین",
        tabDashboard = "داشبورد",
        tabNewInvestigation = "ردیابی جدید",
        tabCases = "بایگانی",
        tabGraph = "گراف ارتباطات",
        tabTasks = "وظایف",
        tabApiSettings = "تنظیمات",
        tabUserMgmt = "مدیریت کاربران و دسترسی‌ها",
        
        stage1Title = "گام ۱: مشخصات هدف و قلمرو",
        stage2Title = "گام ۲: استخراج و یکسان‌سازی تراکنش‌ها",
        stage3Title = "گام ۳: ماتریس طرف‌های مقابل",
        stage4Title = "گام ۴: تطبیق با الگوهای جرم و پولشویی",
        stage5Title = "گام ۵: تحلیل زمانی و تقریب جغرافیایی",
        stage6Title = "گام ۶: گراف تعاملی جریان سرمایه",
        stage7Title = "گام ۷: زنجیره ادله و صدور گزارش",
        nextStage = "گام بعدی تحلیل",
        prevStage = "گام قبلی",
        rerunStage = "تحلیل مجدد با فیلترهای جدید",
        
        caseReferenceNumber = "شماره مرجع پرونده / کلاسه",
        caseTitle = "عنوان پرونده / تحقیق",
        blockchainNetwork = "شبکه بلاکچین",
        targetAddress = "آدرس عمومی هدف جهت ردیابی",
        addressPlaceholder = "آدرس بیت‌کوین (1..., 3..., bc1q..., bc1p...) یا اتریوم (0x...)",
        investigationScope = "محدوده و شرح مقدماتی تحقیق",
        notesAndTags = "برچسب‌ها و یادداشت‌های کارشناس",
        searchDepth = "عمق بررسی ارتباط",
        queryLimit = "سقف دریافت تراکنش‌ها",
        startInvestigation = "آغاز عملیات ردیابی و استخراج ادله",
        addressValidationSuccess = "فرمت آدرس معتبر است و از نظر ساختاری تایید شد",
        addressValidationError = "فرمت آدرس نامعتبر است یا با شبکه انتخابی همخوانی ندارد",
        addressFormatType = "نوع آدرس شناسایی‌شده:",
        
        evidenceLogTitle = "زنجیره ادله و مستندات جرم‌یابی (Evidence Chain)",
        evidenceLogSubtitle = "تفکیک صریح حقایق قطعی داده بلاکچین از محاسبات الگوریتمی، برچسب‌ها و الگوهای رفتاری",
        categoryObservedFact = "حقیقت قطعی داده بلاکچین (Observed Fact)",
        categoryAlgorithmResult = "محاسبه الگوریتمی (Calculation)",
        categoryAttribution = "انتساب و برچسب هویتی (Attribution)",
        categoryBehavioralPattern = "الگوی رفتاری و سوءظن (Pattern Match)",
        categoryTemporalAnalysis = "تحلیل زمانی و توزیع شبانه‌روزی (Temporal)",
        categoryInvestigatorConclusion = "جمع‌بندی کارشناس پرونده (Investigator Note)",
        confidenceDefinitive = "قطعیت ۱۰۰٪ داده بلاکچین",
        confidenceHigh = "احتمال بالا (تایید چندگانه)",
        confidenceMedium = "احتمال متوسط (قانون تحلیلی)",
        confidenceHeuristic = "فرضیه تحلیلی بر اساس نشانه تحلیلی",
        filterAllEvidence = "همه ادله",
        filterOnlyFacts = "فقط حقایق قطعی",
        filterOnlyPatterns = "فقط الگوهای مشکوک",
        
        balance = "موجودی فعلی کیف‌پول",
        totalReceived = "مجموع ورودی ثبت‌شده",
        totalSent = "مجموع خروجی ثبت‌شده",
        totalTransactions = "تعداد کل تراکنش‌ها",
        firstActivity = "اولین تراکنش مشاهده‌شده",
        lastActivity = "آخرین تراکنش مشاهده‌شده",
        uniqueCounterparties = "طرف‌های مقابل یکتا",
        riskIndicatorsDetected = "شاخص‌های ریسک شناسایی‌شده",
        
        customCurrencyRates = "نرخ‌های تبدیل ارزی (USD / تومان)",
        btcUsdRate = "نرخ بیت‌کوین به دلار (BTC/USD)",
        usdTomanRate = "نرخ تتر / دلار به تومان (USDT/TOMAN)",
        equivalentUsd = "معادل دلاری (USD)",
        equivalentToman = "معادل ریالی / تومان",
        editRates = "ویرایش نرخ‌های محاسباتی",
        
        transactionsTitle = "تراکنش‌های یکسان‌سازی‌شده و جریان وجوه",
        txHash = "شناسه تراکنش (TxID)",
        time = "زمان وقوع",
        blockHeight = "شماره بلوک",
        direction = "جهت تراکنش",
        amount = "مبلغ موثر",
        fee = "کارمزد شبکه",
        counterparties = "طرف‌های مقابل",
        dirIncoming = "ورودی (دریافتی)",
        dirOutgoing = "خروجی (ارسالی)",
        dirSelf = "انتقال داخلی (تغییر خرد)",
        dirMixed = "ترکیبی (چندوارد/چندخارج)",
        filterDirection = "فیلتر جهت تراکنش",
        filterMinAmount = "حداقل مبلغ تراکنش",
        
        patternLibraryTitle = "کتابخانه الگوهای جرائم مالی و انطباق رفتاری",
        patternMatchingSubtitle = "مقایسه رفتار تراکنش‌ها با الگوهای شناخته‌شده پولشویی، خردسازی و باج‌افزار",
        similarityScore = "درصد شباهت الگویی",
        matchedIndicatorsTitle = "شاخص‌های رفتاری منطبق:",
        conflictingIndicatorsTitle = "شاخص‌های متعارض / متمایزکننده:",
        missingEvidenceTitle = "ادله و مستندات تکمیلی مورد نیاز:",
        analyticalRecommendation = "پیشنهاد تحلیلی و گام بعدی ردیابی:",
        referenceCasesTitle = "پرونده‌های تاریخی و مرجع مستند",
        viewReferenceCase = "مشاهده مشخصات پرونده مرجع",
        
        temporalAnalysisTitle = "تحلیل زمانی و چرخه شبانه‌روزی (Diurnal Analysis)",
        temporalSubtitle = "توزیع ۲۴ ساعته تراکنش‌ها و ارزیابی آماری سازگاری با مناطق زمانی جهانی",
        hourlyActivityTehran = "توزیع ساعتی بر مبنای منطقه زمانی تهران (IRST)",
        hourlyActivityUtc = "توزیع ساعتی بر مبنای ساعت هماهنگ جهانی (UTC)",
        dayOfWeekDistribution = "توزیع فعالیت در روزهای هفته (شنبه تا جمعه)",
        geographicCompatibilityTitle = "سازگاری آماری با ساعات کاری مناطق جغرافیایی",
        compatibilityPercentage = "درصد سازگاری با ساعات بیداری (۰۸:۰۰ - ۲۰:۰۰)",
        candidateRegion = "منطقه زمانی نامزد",
        workingHoursWindow = "بازه ساعات کاری (UTC)",
        temporalDisclaimer = "هشدار: تطابق زمانی صرفاً مقایسه آماری با ساعات کاری است و به تنهایی اثبات‌کننده حضور فیزیکی در آن منطقه نیست.",
        
        graphTitle = "گراف تعاملی ارتباطات و جریان سرمایه",
        zoomIn = "بزرگ‌نمایی (+)",
        zoomOut = "کوچک‌نمایی (-)",
        resetView = "تنظیم مجدد دید",
        selectNodePrompt = "جهت مشاهده جزئیات یا ایزوله‌سازی، روی هر گره لمس کنید",
        exportGraph = "خروجی گراف (GraphML / JSON)",
        exportPdfReport = "صدور گزارش رسمی جرم‌یابی (PDF)",
        
        counterpartyMatrix = "ماتریس طرف‌های مقابل و ارتباطات متقابل",
        counterpartyAddress = "آدرس طرف مقابل",
        interactionCount = "تعداد دفعات تعامل",
        volumeReceived = "مجموع دریافتی از این آدرس",
        volumeSent = "مجموع ارسالی به این آدرس",
        netFlow = "خالص جریان نقدینگی",
        pairwiseDeepDiveTitle = "تحلیل عمیق رابطه دوطرفه (Address A ↔ Address B)",
        directInteractions = "تعداد تعاملات مستقیم",
        bilateralNetFlow = "خالص تبادل مالی دوجانبه",
        
        exportDossierTitle = "صدور پرونده و مستندات جرم‌یابی",
        exportTxtDossier = "متن کامل پرونده جرم‌یابی (Forensic Dossier TXT)",
        exportCsvDataset = "دیتاست تراکنش‌ها و طرف‌های مقابل (CSV / Excel)",
        exportJsonBundle = "بسته کامل ساختاریافته پرونده (JSON Bundle)",
        downloadDossier = "دریافت و ذخیره فایل گزارش",
        exportSuccessMessage = "گزارش با موفقیت ایجاد و آماده بهره‌برداری شد.",
        
        settingsTitle = "تنظیمات سامانه و مدیریت ارائه‌دهندگان داده (APIs)",
        languageSetting = "زبان رابط کاربری (Language)",
        jalaliCalendarSetting = "نمایش پیش‌فرض تاریخ به تقویم هجری شمسی (جلالی)",
        tehranTimezoneSetting = "نمایش ساعت و تحلیل‌های زمانی بر مبنای منطقه زمانی تهران",
        persianNumeralsSetting = "قالب‌بندی اعداد به ارقام فارسی",
        apiProvidersTitle = "ارائه‌دهندگان داده‌های بلاکچین و کاوشگرها",
        testConnection = "تست اتصال",
        connectionSuccess = "ارتباط با سرویس با موفقیت برقرار شد",
        connectionFailed = "خطا در برقراری ارتباط با سرویس",
        providerHelp = "راهنما و محدودیت‌های سرویس",
        primaryApiKey = "کلید API اصلی (Primary API Key)",
        secondaryApiKey = "کلید API ثانویه / پشتیبان",
        saveSettings = "ذخیره تغییرات",
        userManagementTitle = "مدیریت کاربران و دسترسی‌های تخصصی",
        activeUser = "کاربر فعال:",
        userRole = "نقش سازمانی:",
        togglePermission = "تغییر دسترسی",
        changePasswordTitle = "تغییر رمز عبور کاربر مدیر",
        newPasswordLabel = "رمز عبور جدید (حداقل ۸ کاراکتر)",
        confirmPasswordLabel = "تکرار رمز عبور جدید",
        updatePasswordButton = "ثبت رمز عبور جدید",
        
        loadingBlockchainData = "در حال واکشی داده‌های خام از نود و کاوشگرهای بلاکچین...",
        analyzingPatterns = "در حال پردازش ادله، جریان‌های ورودی/خروجی و الگوهای پولشویی...",
        savingCase = "در حال ذخیره مستندات پرونده در پایگاه داده محلی...",
        deleteCase = "حذف پرونده",
        reopenCase = "بازگشایی و بازبینی پرونده",
        noCasesFound = "هنوز هیچ پرونده‌ای ثبت یا ردیابی نشده است.",
        close = "بستن",
        copyAddress = "کپی آدرس",
        copiedToClipboard = "آدرس در حافظه موقت کپی شد.",
        errorOccurred = "خطایی رخ داده است:",
        disclaimerText = "هشدار قانونی: شباهت‌های الگویی و انتساب‌ها شاخص‌های تحلیلی و آماری بوده و به تنهایی اثبات‌کننده جرم نیستند. سامانه ادله قطعی آن‌چین را از فرضیات تحلیلی تفکیک می‌نماید."
    )

    val stringsEn = ForensicStrings(
        appTitle = "BAYYINAH",
        appSubtitle = "Blockchain Financial Forensics & Evidence Intelligence",
        tabDashboard = "Dashboard",
        tabNewInvestigation = "New Lookup",
        tabCases = "Archives",
        tabGraph = "Network Graph",
        tabTasks = "Tasks",
        tabApiSettings = "Settings",
        tabUserMgmt = "User & Access Control",
        
        stage1Title = "Stage 1: Target Initialization",
        stage2Title = "Stage 2: Activity Discovery & Flows",
        stage3Title = "Stage 3: Counterparty Matrix",
        stage4Title = "Stage 4: Crime-Pattern Matching",
        stage5Title = "Stage 5: Temporal & Geo-Time",
        stage6Title = "Stage 6: Interactive Network Graph",
        stage7Title = "Stage 7: Evidence Chain & Export",
        nextStage = "Next Stage",
        prevStage = "Previous Stage",
        rerunStage = "Rerun with Modified Scope",
        
        caseReferenceNumber = "Case Reference / Docket Number",
        caseTitle = "Investigation Title",
        blockchainNetwork = "Blockchain Network",
        targetAddress = "Target Public Blockchain Address",
        addressPlaceholder = "Bitcoin (1..., 3..., bc1q..., bc1p...) or Ethereum (0x...)",
        investigationScope = "Investigation Scope & Preliminary Hypothesis",
        notesAndTags = "Investigator Notes & Forensic Tags",
        searchDepth = "Hop Search Depth",
        queryLimit = "Transaction Query Limit",
        startInvestigation = "Initialize Investigation & Extract Evidence",
        addressValidationSuccess = "Address format is valid and cryptographically verified",
        addressValidationError = "Invalid address format or mismatch with selected network",
        addressFormatType = "Identified Address Standard:",
        
        evidenceLogTitle = "Forensic Evidence Chain & Fact Audit",
        evidenceLogSubtitle = "Strict ontological separation of On-Chain Facts, Algorithms, Attributions, and Heuristics",
        categoryObservedFact = "Directly Observed Fact (On-Chain)",
        categoryAlgorithmResult = "Algorithmic Calculation (Derived)",
        categoryAttribution = "Entity Attribution & Label (OSINT)",
        categoryBehavioralPattern = "Suspicious Behavioral Pattern (Heuristic)",
        categoryTemporalAnalysis = "Temporal & Diurnal Analysis (Statistical)",
        categoryInvestigatorConclusion = "Investigator Assessment (Manual)",
        confidenceDefinitive = "100% Deterministic On-Chain Fact",
        confidenceHigh = "High Confidence (Multi-Source)",
        confidenceMedium = "Medium Confidence (Heuristic Match)",
        confidenceHeuristic = "Probabilistic Hypothesis",
        filterAllEvidence = "All Evidence",
        filterOnlyFacts = "Only On-Chain Facts",
        filterOnlyPatterns = "Only Suspicious Patterns",
        
        balance = "Current Ledger Balance",
        totalReceived = "Total Received Volume",
        totalSent = "Total Sent Volume",
        totalTransactions = "Total Confirmed Transactions",
        firstActivity = "Earliest Observed Activity",
        lastActivity = "Latest Observed Activity",
        uniqueCounterparties = "Unique Counterparties",
        riskIndicatorsDetected = "Risk Indicators Detected",
        
        customCurrencyRates = "Currency Conversion Rates (USD / Toman)",
        btcUsdRate = "Bitcoin / USD Rate (BTC/USD)",
        usdTomanRate = "USDT / Toman Rate (USDT/TOMAN)",
        equivalentUsd = "USD Equivalent",
        equivalentToman = "Toman Equivalent",
        editRates = "Configure Rates",
        
        transactionsTitle = "Normalized Transactions & Flow Accounting",
        txHash = "Transaction Hash (TxID)",
        time = "Execution Time",
        blockHeight = "Block Height",
        direction = "Flow Direction",
        amount = "Relevant Value",
        fee = "Network Fee",
        counterparties = "Counterparties",
        dirIncoming = "Incoming (Deposit)",
        dirOutgoing = "Outgoing (Withdrawal)",
        dirSelf = "Self Transfer / Consolidation",
        dirMixed = "Mixed Flow (Multi-In/Out)",
        filterDirection = "Filter Direction",
        filterMinAmount = "Min Value Filter",
        
        patternLibraryTitle = "Crime-Pattern Library & Behavioral Matching",
        patternMatchingSubtitle = "Comparing observed flows against known AML, peeling-chain, and smurfing typologies",
        similarityScore = "Pattern Similarity Score",
        matchedIndicatorsTitle = "Matched Behavioral Indicators:",
        conflictingIndicatorsTitle = "Conflicting / Distinguishing Indicators:",
        missingEvidenceTitle = "Required Corroborating Evidence:",
        analyticalRecommendation = "Analytical Recommendation & Next Lead:",
        referenceCasesTitle = "Public Reference Cases & Typologies",
        viewReferenceCase = "Inspect Reference Case",
        
        temporalAnalysisTitle = "Temporal & Diurnal Analysis",
        temporalSubtitle = "24-hour activity rhythm and statistical compatibility with global business timezones",
        hourlyActivityTehran = "Hourly Distribution in Asia/Tehran Local Time (IRST)",
        hourlyActivityUtc = "Hourly Distribution in UTC",
        dayOfWeekDistribution = "Day of Week Activity Profile",
        geographicCompatibilityTitle = "Statistical Compatibility with Regional Working Hours",
        compatibilityPercentage = "Compatibility with Daytime Activity (08:00 - 20:00)",
        candidateRegion = "Candidate Timezone Region",
        workingHoursWindow = "Working Hours Window (UTC)",
        temporalDisclaimer = "Notice: Temporal correlation reflects statistical daytime compatibility and does not establish physical location.",
        
        graphTitle = "Interactive Relationship & Flow Graph",
        zoomIn = "Zoom In (+)",
        zoomOut = "Zoom Out (-)",
        resetView = "Reset View",
        selectNodePrompt = "Tap any node to inspect balance, counterparties, or isolate connections",
        exportGraph = "Export Graph (GraphML / JSON)",
        exportPdfReport = "Generate Forensic Report (PDF)",
        
        counterpartyMatrix = "Counterparty Matrix & Flow Ledger",
        counterpartyAddress = "Counterparty Address",
        interactionCount = "Interactions",
        volumeReceived = "Volume Received",
        volumeSent = "Volume Sent",
        netFlow = "Net Volume Flow",
        pairwiseDeepDiveTitle = "Pairwise Relationship Deep Dive (Address A ↔ Address B)",
        directInteractions = "Direct Transactions",
        bilateralNetFlow = "Bilateral Net Flow",
        
        exportDossierTitle = "Evidence Dossier & Multi-Format Export",
        exportTxtDossier = "Official Forensic Text Dossier (TXT)",
        exportCsvDataset = "Transactions & Counterparty Dataset (CSV / Excel)",
        exportJsonBundle = "Structured Investigation Bundle (JSON)",
        downloadDossier = "Generate & Download Dossier",
        exportSuccessMessage = "Forensic report dataset compiled successfully.",
        
        settingsTitle = "Platform Configuration & API Provider Management",
        languageSetting = "UI Language",
        jalaliCalendarSetting = "Default to Solar Hijri (Jalali) Calendar",
        tehranTimezoneSetting = "Display timestamps in Asia/Tehran Local Time",
        persianNumeralsSetting = "Format Numbers with Persian Digits",
        apiProvidersTitle = "Blockchain Explorer & Node Providers",
        testConnection = "Test Connection",
        connectionSuccess = "Connection established successfully",
        connectionFailed = "Connection failed",
        providerHelp = "Provider Documentation & Limits",
        primaryApiKey = "Primary API Key",
        secondaryApiKey = "Secondary API Key",
        saveSettings = "Save Configuration",
        userManagementTitle = "User Accounts & Role-Based Access Control",
        activeUser = "Active User:",
        userRole = "Role:",
        togglePermission = "Toggle Permission",
        changePasswordTitle = "Admin Password Update",
        newPasswordLabel = "New Secure Password (Min 8 chars)",
        confirmPasswordLabel = "Confirm New Password",
        updatePasswordButton = "Update Password",
        
        loadingBlockchainData = "Querying blockchain node and explorer endpoints...",
        analyzingPatterns = "Normalizing flows, calculating velocity, and matching risk indicators...",
        savingCase = "Persisting investigation bundle to local secure storage...",
        deleteCase = "Delete Case",
        reopenCase = "Reopen & Review Case",
        noCasesFound = "No investigation cases found in local archive.",
        close = "Close",
        copyAddress = "Copy Address",
        copiedToClipboard = "Address copied to clipboard.",
        errorOccurred = "An error occurred:",
        disclaimerText = "Legal Notice: Pattern similarities and attributions are analytical indicators and do not establish criminal conduct. The system strictly isolates verifiable on-chain facts from analytical inferences."
    )

    fun getStrings(language: AppLanguage): ForensicStrings {
        return if (language == AppLanguage.ENGLISH) stringsEn else stringsFa
    }
}
